apiVersion: v1
kind: ConfigMap
metadata:
  name: phonebook-config
  namespace: api-backend
data:
  APP_NAME: "PhoneBookAPI"
  APP_SCHEMA: "http"
  APP_HOST: "localhost"
  APP_PORT: "8000"
  APP_ROUTE_PREFIX: "/api"
  DB_TYPE: "mysql"
  DB_HOST: ""
  DB_PORT: "3306"
  DB_DATABASE: ""
  DB_LOGGING: "true"
  LOGGING_OUTPUT: "dev"
---
apiVersion: v1
kind: Secret
metadata:
  name: phonebook-secret
  namespace: api-backend
type: Opaque
data:
  DB_USERNAME: ""
  DB_PASSWORD: ""
