---
apiVersion: v1
kind: Namespace
metadata:
  name: api-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook
  namespace: api-backend
  labels:
    app: phonebook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phonebook
  template:
    metadata:
      labels:
        app: phonebook
    spec:
      containers:
      - name: phonebook
        image: docker.io/zedanlab/phonebookapi-image:latest
        env:
          - name: APP_NAME
            valueFrom:
                configMapKeyRef:
                  name: phonebook-config
                  key: APP_NAME
          - name: APP_SCHEMA
            valueFrom:
                configMapKeyRef:
                  name: phonebook-config
                  key: APP_SCHEMA
          - name: APP_HOST
            valueFrom:
                configMapKeyRef:
                  name: phonebook-config
                  key: APP_HOST
          - name: APP_PORT
            valueFrom:
                configMapKeyRef:
                  name: phonebook-config
                  key: APP_PORT
          - name: APP_ROUTE_PREFIX
            valueFrom:
                configMapKeyRef:
                  name: phonebook-config
                  key: APP_ROUTE_PREFIX
          - name: DB_TYPE
            valueFrom:
                configMapKeyRef:
                  name: phonebook-config
                  key: DB_TYPE
          - name: DB_HOST
            valueFrom:
                configMapKeyRef:
                  name: phonebook-config
                  key: DB_HOST
          - name: DB_PORT
            valueFrom:
                configMapKeyRef:
                  name: phonebook-config
                  key: DB_PORT
          - name: DB_DATABASE
            valueFrom:
                configMapKeyRef:
                  name: phonebook-config
                  key: DB_DATABASE
          - name: DB_LOGGING
            valueFrom:
                configMapKeyRef:
                  name: phonebook-config
                  key: DB_LOGGING
          - name: LOGGING_OUTPUT
            valueFrom:
                configMapKeyRef:
                  name: phonebook-config
                  key: LOGGING_OUTPUT
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: phonebook-secret
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: phonebook-secret
                key: DB_PASSWORD
        ports:
        - name: http
          containerPort: 8000
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: phonebook
  namespace: api-backend
spec:
  type: ClusterIP
  selector:
    app: phonebook
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8000